### ISSUE TITLE
Add commas in Views and Likes

### ISSUE THREAD

**Issue by lihengcao** [adrinu/adriMUSIC#1]
![image](https://user-images.githubusercontent.com/20694415/209455454-0d764b56-7e3a-40e1-b48b-0c9b36d26a89.png)

When these numbers get larger, they get harder to read. Adding commas would be a nice touch.

**Comment by adrinu** [comment]
mamaguebo

**Comment by adrinu** [comment]
> ![image](https://user-images.githubusercontent.com/20694415/209455454-0d764b56-7e3a-40e1-b48b-0c9b36d26a89.png)
> 
> When these numbers get larger, they get harder to read. Adding commas would be a nice touch.

mamaguebo

**Comment by lihengcao** [comment]
maybe something like this? https://www.geeksforgeeks.org/print-number-commas-1000-separators-python/

**Comment by adrinu** [comment]
Fixed in [023fad2](https://github.com/adrinu/adriMUSIC/commit/023fad2e7215bbd61d2284b36d7ede9152cc6cd2)
